src/constants/constants.ts, src/modules/item/service.ts, src/modules/search/queryBuilder.ts, src/modules/search/search.spec.ts, src/modules/search/service.ts
fix:
* proxy service test suite
* only show results if `_score` is > 0.5 if search terms were entered
* switch educationLevel from `lom_typical_age_range` to `lom_context`
* avoid console.error when aggregation value is null
closes: 
* https://district01.atlassian.net/browse/AVO2-402
* https://district01.atlassian.net/browse/AVO2-403
=> fix: only show results with score > 0.5, fix tests, avoid console error

server/src/modules/data/controller.ts, server/src/modules/data/route.ts, server/src/modules/data/service.ts
The nginx for avo adds a unique trace id header to every request that comes into viaa
This header needs to be forwarded to the graphql instance, so logging entries can be linked to the incoming request.
This is a POC since we can only verify this once we push this to QAS and then use the remote url (which doesn't exist yet) for the client app to trigger an event.
=> feat: add trace id to graphql queries

server/src/modules/auth/controller.ts, server/src/modules/auth/route.ts, server/src/modules/data/controller.ts, server/src/modules/data/route.ts
Je kan dit enkel testen door in te loggen met een andere account dan de account die de opdracht gemaakt heeft, want de owner mag altijd de opdracht bekijken.
De types errors zijn:
```
export enum AssignmentRetrieveError {
DELETED = 'DELETED',
NOT_YET_AVAILABLE = 'NOT_YET_AVAILABLE',
PAST_DEADLINE = 'PAST_DEADLINE',
}
```
=> feat(data): add retrieve errors when getting assignments

server/src/modules/event-logging/controller.ts
Walter:
> ip ontbreekt nog precies
> @Bert Verhelst "intern" zal niet werken je moet een ip geven
> je kan eventueel 127.0.0.1 zetten dat is zelfde als localhost
=> fix(event-logging): default to localhost for event generated inside viaa

server/package-lock.json, server/package.json, server/src/modules/auth/controller.ts, server/src/modules/auth/idps/hetarchief/controller.ts, server/src/modules/auth/idps/hetarchief/route.ts, server/src/modules/stamboek-validate/controller.ts
Allow teachers to register
Import notes for testing:
* you can register using your own email address
* if you want to try multiple times, you can add a "." character in your gmail emailaddress which creates an alias. Email will still be received on your regular gmail address (eg: ve.rhelstbert@gmail.com)
* Do not use a "+" sign, since the ldap database can't handle this and the ssum registration page of viaa doesn't correctly escape the + char
* For the stamboekNumber, you can use the stamboek number in 1password under "viaa test stamboek number"
=> fix(registration-flow): fix issues with registration, add test stamboek

server/src/modules/organization/organization.spec.ts, server/src/modules/organization/queries.gql.ts, server/src/modules/organization/service.ts
1. Get organizations from API.
2. Delete organizations from GraphQL.
3. Fill organizations from GraphQL.
=> AVO2-599: Cache organizations in GraphQL on a nightly basis.

server/src/modules/auth/controller.ts, server/src/modules/auth/idps/hetarchief/route.ts, server/src/modules/auth/idps/smartschool/route.ts, server/src/modules/auth/route.ts, server/src/shared/helpers/error-redirect-client.ts
This PR checks if the user's ldap account has the avo application in its allowed apps
and it also adds action buttons for all error view redirects
This PR has a client twin: https://github.com/viaacode/avo2-client/pull/372
=> fix(auth): redirect to error page if no avo group + added action buttons

server/src/modules/auth/idps/hetarchief/controller.ts, server/src/modules/auth/service.ts
This is a temporary fix until the ssum takes over the duties of setting ldap apps/groups
=> fix(auth): add avo app by id instead of name through ldap api

server/src/modules/auth/controller.ts, server/src/modules/auth/idp-helper.ts, server/src/modules/auth/idps/hetarchief/controller.ts, server/src/modules/auth/idps/hetarchief/route.ts, server/src/modules/auth/idps/smartschool/controller.ts, server/src/modules/auth/queries.gql.ts, server/src/modules/auth/service.ts
Currently when a user logs in, we link their ldap user to their avo user by email
This is bad practice since email can change. This PR makes sure users are linked through the idp_map table.
I've also included a patch, so existing users that try to login will be linked through the idp_table, by first linking them through their email. This patch can be removed in the future
=> fix(auth): link accounts through ipd map instead of email

server/src/modules/auth/controller.ts, server/src/modules/auth/idps/hetarchief/controller.ts, server/src/modules/auth/idps/hetarchief/route.ts, server/src/modules/auth/idps/smartschool/controller.ts, server/src/modules/auth/queries.gql.ts, server/src/modules/auth/service.ts, server/src/modules/profile/controller.ts
closes: https://district01.atlassian.net/browse/AVO2-943
Features:
* When a user tries to login using their archief account, and they have the avo app permission on their ldap account, we should create the corresponding avo user and profile.
* When creating a user set their appropriate user groups based on the ldap organizational status field
You can test this by logging in with one of the test accounts (in 1password) and seeing that you can login since those accounts do not have an avo user/profile yet (except for the eindredacteur test acount)
=> feat(auth): create user on login, set permission groups

server/src/modules/search/service.ts
since _id will be switched over to the item uuid
=> fix(search): get result item external id from _source instead of _id

server/package-lock.json, server/package.json, server/src/app.ts, server/src/modules/content-pages/controller.ts, server/src/modules/content-pages/queries.gql.ts, server/src/modules/content-pages/route.ts, server/src/modules/content-pages/service.ts, server/src/modules/klaar/controller.ts, server/src/modules/navigation-items/controller.ts, server/src/modules/navigation-items/queries.gql.ts, server/src/modules/navigation-items/route.ts
closes: https://district01.atlassian.net/browse/AVO2-1041
client twin:
https://github.com/viaacode/avo2-client/pull/464
Test urls:
* http://localhost:8080/test-media-grid-bert
* http://localhost:8080/klaar/archief
=> feat(content-pages): add route to load content page with search results

server/src/modules/organization/service.ts
closes: https://meemoo.atlassian.net/browse/AVO-224
The  ORGANIZATIONS_API_TOKEN has been added to all environment variables
This value will have to be filled in by tina or herwig in openshift
They should only enable authentication once this PR has been deployed to QAS and PRD
=> feat(organizations): add token to org api requests

server/src/modules/search/queryBuilder.ts
closes: https://meemoo.atlassian.net/browse/AVO-225
It's not a problem for people to be able to add wildcards into a search query. Escaping characters seems to cause issues with the search results not matching the expected results.
=> fix(search): remove escape function from elasticsearch search term

server/src/modules/auth/idp-helper.ts, server/src/modules/auth/queries.gql.ts
otherwise you can't login with the test accounts, eg:
accounts+eindredacteur@meemoo.be
=> fix(idp-map): avoid throwing error when idp map already exists

server/src/modules/auth/idps/hetarchief/route.ts, server/src/modules/auth/idps/klascement/route.ts, server/src/modules/auth/idps/smartschool/route.ts
part of https://district01.atlassian.net/browse/AVO2-1048
client twin: https://github.com/viaacode/avo2-client/pull/525
This way users can point to {{PROXY_URL}}/auth/smartschool/login without having to provide the ?redirectToUrl query param
=> fix(auth): add fallback for redirect to params in login routes

server/src/modules/assets/service.ts
closes: https://meemoo.atlassian.net/browse/AVO-170
The token expiry date comparison was the other way around, causing the token to get requested on every request, until one day no one made a request, and then the token was never renewed.
=> fix(assets): ensure s3 token gets renewed correctly

server/src/shared/helpers/error.ts, server/src/shared/helpers/omit-by-deep.ts
otherwise we miss some vital info because it is outputted as: [Object: object]
=> fix(error): output error objects up to 20 inner exception levels deep

server/src/modules/campaign-monitor/controller.ts, server/src/modules/campaign-monitor/route.ts, server/src/modules/campaign-monitor/types.ts
closes: https://meemoo.atlassian.net/browse/AVO-939
custom fields sent to campaign monitor should be:
```
{
"gebruikersrol": "Lesgever",
"gebruikersgroep": "Lesgever secundair",
"stamboeknummer": null,
"is_uitzondering": "false",
"firstname": "Lesgever",
"lastname": "Account",
"graad": "Secundair onderwijs, Lager onderwijs",
"vakken": "lichamelijke opvoeding, muzische vorming",
"school_postcodes": "2970, 9300, 8511, 8870",
"school_ids": "100065, 104851, 18788, 19497, 8284",
"school_campus_ids": "104851-2-111, 18788-1-111, 19497-1-111, 8284-1-111",
"school_namen": "GO! internaat medisch pedagogisch instituut Zonnebos 's Gravenwezel, Vrije Basisschool - DvM, Vrije Basisschool, Vrije Basisschool - Heilig-Hart"
}
```
=> fix(campaign-monitor): change custom fields to comma separated strings

server/src/modules/content-pages/consts.ts, server/src/modules/content-pages/controller.ts, server/src/modules/content-pages/queries.gql.ts, server/src/modules/content-pages/service.ts
closes:
* AVO-969
* AVO-372
test pages:
* media tile manual selected audio item: http://localhost:8080/media-tegels-in-modal-test
* media player selected mam audio item: http://localhost:8080/audio-on-logged-out-content-page
=> fix(content-pages): resolve manual tiles as well, set audio still

server/src/modules/campaign-monitor/controller.ts
part of: https://meemoo.atlassian.net/browse/AVO-926
When we update custom fields in campaign monitor after a change was made to the user properties, we should not call the unsubscribe functions again, since those don't need updated custom fields and we get errors if we try: Failed to unsubscribe from newsletter list
=> fix(campaign-monitor): during refesh custom fields skip unsubscribes

server/src/modules/auth/idps/hetarchief/route.ts
since we already check the ldap object for the avo app and users with an ldap account do not use the is_blocked status
=> fix(hetarchief-route): remove check on is_blocked

server/package-lock.json, server/package.json, server/src/modules/collections/collections.controller.ts
closes: https://meemoo.atlassian.net/browse/AVO-1243
example private bundle: http://localhost:8080/bundels/0edd4e40-5957-435d-9e54-039261553167
before this fix, fetching a private collection without being loggged in would give you this error:
After the fix:
=> fix(collections-controller): safely get permissions from profile

server/src/modules/auth/idps/hetarchief/route.ts
closes: https://meemoo.atlassian.net/browse/AVO-1283
before: login loop:
after: clear error message:
=> fix(auth-het-archief-route): redirect to error when no role from ldap

server/src/modules/content-pages/controller.ts, server/src/modules/content-pages/queries.gql.ts, server/src/modules/content-pages/route.ts, server/src/modules/content-pages/service.ts, server/src/modules/content-pages/types.ts
part of: https://meemoo.atlassian.net/browse/AVO-356
add counts for each label in overview endpoint:
```json
"app_content_labels": [
{
"label": "Lesgevers",
"content_content_labels_aggregate": {
"aggregate": {
"count": 3
}
}
},
{
"label": "Leerlingen",
"content_content_labels_aggregate": {
"aggregate": {
"count": 0
}
}
}
]
```
=> feat(content-pages): return counts of pages for each label

server/src/modules/campaign-monitor/service.ts
closes: https://meemoo.atlassian.net/browse/AVO-1320
escape + symbol in email addresses for the change email route as well
=> fix(campaign-monitor): fix issue with update email call: escaping +

server/src/modules/auth/route.ts, server/src/modules/content-pages/controller.ts, server/src/modules/content-pages/queries.gql.ts, server/src/modules/content-pages/route.ts, server/src/modules/content-pages/service.ts
closes: https://meemoo.atlassian.net/browse/AVO-1095
```
/content-pages/update-published-dates
```
When calling this route the content page published_at date will be updated according to publish_at and depublish_at fields.
```graphql
mutation publishContentPages($now: timestamptz, $publishedAt: timestamptz) {
publish_content_pages: update_app_content(
where: {
_or: [
{publish_at: {_lte: $now, _is_null: false}, depublish_at: {_gte: $now, _is_null: false}},
{publish_at: {_lte: $now, _is_null: false}, depublish_at: {_is_null: true}},
{publish_at: {_is_null: true}, published_at: {_gte: $now, _is_null: false}}
],
published_at: {_is_null: true}
},
_set: {published_at: $publishedAt}
) {
affected_rows
}
unpublish_content_pages: update_app_content(
where: {
depublish_at: {_lt: $now, _is_null: …
```
=> feat(content-pages): add route to update published_at dates

server/src/modules/auth/idps/hetarchief/service.ts
workaround for error:
Error: SAML Assertion signature check failed! (checked 1 certificate(s))
=> fix(hetarchief-service): disable certificate check for localhost SAML

server/src/modules/auth/idps/hetarchief/controller.ts
closes: https://meemoo.atlassian.net/browse/AVO-1332
now all required fields should be synced in both directions.
acm => avo:
avo => acm
=> fix(auth-hetarchief-controller): allow multiple companies with oormerk

server/src/modules/auth/idps/hetarchief/controller.ts
closes: https://meemoo.atlassian.net/browse/AVO-1461
Client PR: https://github.com/viaacode/avo2-client/pull/1145
This mainly fixes this scenario:
* getest met ineke.vandam+1
* via acm AVO app verwijderd+syncen
* aanmelden lukt niet op avo
* via acm AVO app terug toevoegen + syncen
* aanmelden lukt niet op avo
=> fix(hetarchief-controller): is_blocked follows avo app in ACM

server/package-lock.json, server/package.json, server/src/app.ts, server/src/libs.d.ts, server/src/modules/not-found/404.html, server/src/modules/not-found/not-found.route.ts
part of: https://meemoo.atlassian.net/browse/AVO-1657
When the client detects a route that doesn't exist, it can redirect the browser to the /not-found route on the server. Which returns a static 404 page with status code: 404 instead of the 200 the client returns
=> feat(not-found-route): add route to serve true 404 page for client
