viaacode/avo2-proxy

- src/modules/search/controller.ts
- src/modules/search/service.ts
You can get some collections when you search for:
```
Onderwijs Hilde Crevits en vice-premier Alexander De Croo
```
> feat: all searching of both or one of the search indexes for coll, items

- server/jest.config.js
- server/src/app.ts
- server/src/modules/data/controller.ts
- server/src/modules/data/data.spec.ts
- server/src/modules/data/route.ts
- server/src/modules/player-ticket/service.ts
- server/test/integration/core/fallback.spec.ts
> fix: cleanup and add data route tests

- server/src/modules/video-stills/controller.ts
- server/src/modules/video-stills/queries.gql.ts
- server/src/modules/video-stills/route.ts
- server/src/modules/video-stills/service.ts
- server/src/modules/video-stills/validation.ts
- server/src/modules/video-stills/video-stills.spec.ts
- server/src/shared/helpers/duration.ts
> fix: only return first video still after startTime for every video id

- server/src/modules/data/route.ts
- server/src/modules/fallback/fallback.spec.ts
- server/src/modules/organization/organization.spec.ts
- server/src/modules/organization/service.ts
- server/src/modules/player-ticket/route.ts
- server/src/modules/search/route.ts
- server/src/modules/stamboek-validate/route.ts
- server/src/modules/video-stills/route.ts
- server/src/shared/middleware/is-authenticated.ts
> fix: move route auth to middleware + add organization route tests

- server/src/modules/auth/controller.ts
- server/src/modules/auth/queries.gql.ts
- server/src/modules/auth/route.ts
- server/src/modules/auth/service.ts
> Feature: return userinfo + permissions when logging in

- server/src/modules/search/controller.ts
> fix(search): update elasticsearch indeces

- package.json
- server/package-lock.json
- server/package.json
- server/src/app.ts
- server/src/modules/data/controller.ts
- server/src/modules/data/service.ts
- server/src/modules/event-logging/controller.ts
- server/src/modules/event-logging/queries.gql.ts
- server/src/modules/event-logging/route.ts
- server/src/modules/event-logging/service.ts
- server/src/modules/event-logging/types.ts
- server/src/modules/player-ticket/route.ts
POC for task: https://district01.atlassian.net/browse/AVO2-647
> feature: event logging new format

- server/src/modules/search/controller.ts
- server/src/modules/search/route.ts
- server/tsconfig.json
https://district01.atlassian.net/browse/AVO2-298
> feat(related-items): implement related items route for items and coll.

- server/src/modules/search/controller.ts
- server/src/modules/search/queries.gql.ts
Private collections are not indexed by elasticsearch, so we need to pas the title and description instead of the id to elasticsearch
Otherwise you get an empty list
> fix(related-items-route): fix related coll. query for private coll.

- server/src/modules/auth/controller.ts
- server/src/modules/auth/idps/smartschool/service.ts
- server/src/modules/auth/route.ts
- server/src/modules/auth/service.ts
so client doesn't have to deal with keeping track of the logout path
> feat(auth): provide global logout route

- server/package-lock.json
- server/package.json
- server/src/app.ts
- server/src/modules/event-logging/controller.ts
- server/src/modules/event-logging/queries.gql.ts
- server/src/modules/event-logging/route.ts
- server/src/modules/event-logging/service.ts
- server/src/modules/event-logging/types.ts
update event format to: https://viaadocumentation.atlassian.net/wiki/spaces/COMP/pages/1019019307/Event+logging
This PR requires the typings repo PR: https://github.com/viaacode/avo2-typings/pull/27
> feat(event-logging): update event logging format

- server/src/modules/event-logging/route.ts
Otherwise the collections page on qas loads very slowly because the logging on qas fails
> fix(event-logging): avoid keeping client waiting for events being logged

- server/src/modules/auth/idps/hetarchief/controller.ts
- server/src/modules/auth/queries.gql.ts
- server/src/modules/auth/service.ts
- server/src/modules/education-organizations/service.ts
Fixing this now since i couldn't test this before because of the select onchange bug
> fix(profile,educ.orgs): fix issues with saving, add orgs to profile

- server/src/modules/auth/idps/hetarchief/route.ts
- server/src/modules/auth/idps/smartschool/controller.ts
- server/src/modules/auth/idps/smartschool/route.ts
- server/src/modules/auth/queries.gql.ts
- server/src/modules/auth/route.ts
- server/src/modules/search/route.ts
closes: https://district01.atlassian.net/browse/AVO2-158
This PR has a client twin: https://github.com/viaacode/avo2-client/pull/286
> feat(smartschool-login): allow teachter to login/logout using SS

- server/src/app.ts
- server/src/modules/auth/queries.gql.ts
- server/src/modules/auth/service.ts
- server/src/modules/navigation-items/controller.ts
- server/src/modules/navigation-items/queries.gql.ts
- server/src/modules/navigation-items/route.ts
required for frontend dynamic navbars since we cannot use the data route yet, since we might not be logged in yet
https://district01.atlassian.net/browse/AVO2-923
> feat(navigation-items): expose navigation items for specific user

- server/src/modules/assets/controller.ts
- server/src/modules/assets/queries.gql.ts
- server/src/modules/assets/route.ts
- server/src/modules/assets/service.ts
closes: https://district01.atlassian.net/browse/AVO2-373
Test this with this client PR: https://github.com/viaacode/avo2-client/pull/369
> fix(assets): manage assets and keep track of them in the graphql db

- server/src/modules/zendesk/controller.ts
- server/src/modules/zendesk/route.ts
- server/src/modules/zendesk/service.ts
closes: https://district01.atlassian.net/browse/AVO2-561
> feat(zendesk): add route to upload files to zendesk and return the url

- server/src/modules/core/middleware/error.ts
- server/src/modules/search/controller.ts
- server/src/modules/search/queryBuilder.ts
client twin: https://github.com/viaacode/avo2-client/pull/414
> fix(search): allow more search result sort orders, improve error logging

- server/src/modules/auth/idps/hetarchief/controller.ts
- server/src/modules/auth/idps/hetarchief/route.ts
This happens when you start the server locally without being connected to the vpn
> fix(auth): show error to user when server can't reach graphql

- server/src/modules/content-pages/service.ts
- server/src/modules/search/controller.ts
- server/src/modules/search/queries.gql.ts
- server/src/modules/search/route.ts
closes: 
* https://district01.atlassian.net/browse/AVO2-1046
* https://meemoo.atlassian.net/browse/AVO-93
Twin on the client: https://github.com/viaacode/avo2-client/pull/495
> fix(related-items): fix related items, allow search bundles

- server/src/modules/auth/controller.ts
- server/src/modules/auth/idps/hetarchief/controller.ts
- server/src/modules/auth/idps/hetarchief/route.ts
- server/src/modules/auth/queries.gql.ts
closes: https://district01.atlassian.net/browse/AVO2-460
twin PR: https://github.com/viaacode/avo2-client/pull/485
> feat(auth): add accept conditions to check login response

- server/src/modules/auth/idps/hetarchief/controller.ts
- server/src/modules/auth/idps/hetarchief/route.ts
- server/src/modules/auth/queries.gql.ts
- server/src/modules/auth/service.ts
- server/src/modules/auth/types.ts
closes: https://district01.atlassian.net/browse/AVO2-985
related to: https://meemoo.atlassian.net/browse/DEV-708
> feat(auth): sync user groups with ldap when user logs in

- server/src/modules/content-pages/controller.ts
- server/src/modules/content-pages/route.ts
- server/src/modules/content-pages/service.ts
- server/src/modules/search/controller.ts
- server/src/modules/search/queryBuilder.ts
- server/src/modules/search/service.ts
closes: https://meemoo.atlassian.net/browse/AVO-214
client twin PR: https://github.com/viaacode/avo2-client/pull/500
> fix(media-tile-grid): allow select of bundles,fix preview of media grids

- server/src/app.ts
- server/src/modules/auth/controller.ts
- server/src/modules/auth/idps/klascement/controller.ts
- server/src/modules/auth/idps/klascement/route.ts
- server/src/modules/auth/idps/klascement/service.ts
- server/src/modules/auth/idps/smartschool/controller.ts
- server/src/modules/auth/idps/smartschool/route.ts
- server/src/modules/auth/idps/smartschool/service.ts
- server/src/modules/profile/controller.ts
closes: 
* https://district01.atlassian.net/browse/AVO2-159
* https://district01.atlassian.net/browse/AVO2-263
client twin PR: https://github.com/viaacode/avo2-client/pull/497
> feat(auth): add klascement oauth login

- server/package-lock.json
- server/package.json
- server/src/app.ts
- server/src/modules/interactive-tours/controller.ts
- server/src/modules/interactive-tours/queries.gql.ts
- server/src/modules/interactive-tours/route.ts
- server/src/modules/interactive-tours/service.ts
closes: https://meemoo.atlassian.net/browse/AVO-232
Client twin PR: https://github.com/viaacode/avo2-client/pull/502
> feat(interactive-tour): add routes to get tours when user is logged out

- server/src/modules/content-pages/queries.gql.ts
part of: https://meemoo.atlassian.net/browse/AVO-566
> fix(content-pages): fetch thumbnail for content page route

- server/src/modules/auth/idps/hetarchief/route.ts
- server/src/modules/content-pages/route.ts
also removed workaround for linking existing avo user ids to ldap uuids.
> fix(auth): redirect to register route after setting ldap obj on session

- server/src/modules/auth/queries.gql.ts
- server/src/modules/auth/types.ts
part of: https://meemoo.atlassian.net/browse/DEV-781
> fix(user): remove id from gql queries, this has been replaced by uid

- server/src/modules/content-pages/controller.ts
closes: https://meemoo.atlassian.net/browse/AVO-333
client twin: https://github.com/viaacode/avo2-client/pull/555
> feat(content-page): allow publish/unpublish content pages

- server/src/modules/organization/service.ts
closes: https://meemoo.atlassian.net/browse/AVO-646
Duplicate org ids:
- OR-8k74w2m
- OR-4t6f286
- OR-b853h47
- OR-6h4cq10
- OR-pk07167
- OR-hq3rz04
- OR-cz3245m
> fix(organizations): avoid crashing when the org api returns duplicates

- server/package-lock.json
- server/package.json
- server/src/modules/auth/controller.ts
- server/src/modules/auth/idp-helper.ts
- server/src/modules/auth/idps/hetarchief/controller.ts
- server/src/modules/auth/idps/smartschool/controller.ts
- server/src/modules/auth/idps/smartschool/route.ts
- server/src/modules/auth/queries.gql.ts
- server/src/modules/auth/types.ts
part of: https://meemoo.atlassian.net/browse/AVO-9
> fix(smartschool): fix linking smartschool accounts

- server/src/modules/navigation-items/queries.gql.ts
- Added tooltip on navigation items. (AVO-334)
- Made label optional (AVO-59)
- Made tooltip configurable in menu items. (AVO-334)
Has client twin. https://github.com/viaacode/avo2-client/pull/582
> AVO-334 & AVO-59 / nav tooltip

- server/src/modules/auth/idps/hetarchief/controller.ts
- server/src/modules/auth/queries.gql.ts
- server/src/modules/auth/service.ts
closes:  https://meemoo.atlassian.net/browse/AVO-680
> fix(auth): stop setting avo group in ldap, ssum does this from now on

- server/src/modules/content-pages/controller.ts
part of: https://meemoo.atlassian.net/browse/AVO-215
client PR: https://github.com/viaacode/avo2-client/pull/620
> fix(media-tiles): ignore incomplete media items + do not remove query

- server/src/modules/assets/controller.ts
part of: https://meemoo.atlassian.net/browse/AVO-709
Proxy pr: https://github.com/viaacode/avo2-client/pull/634
> fix(assets): check lowercase file extensions, so .JPG is also valid

- server/src/modules/assets/controller.ts
- server/src/modules/assets/route.ts
part of: https://meemoo.atlassian.net/browse/AVO-162
> feat(assets): allow video upload in asset route

- server/src/shared/helpers/error-redirect-client.ts
part of: https://meemoo.atlassian.net/browse/AVO-675
client pr: https://github.com/viaacode/avo2-client/pull/643
> fix(auth): logout before showing login error

- server/src/modules/campaign-monitor/const.ts
- server/src/modules/campaign-monitor/controller.ts
- server/src/modules/campaign-monitor/route.ts
- server/src/modules/campaign-monitor/service.ts
- server/src/modules/campaign-monitor/types.ts
Client twin:https://github.com/viaacode/avo2-client/pull/645
> feat(newsletter): (un)subscribe to list

- server/src/modules/klaar/controller.ts
- server/src/shared/middleware/session.ts
closes: https://meemoo.atlassian.net/browse/AVO-781
```json
{
"uuid": "20200519",
"message": {
"subject": "coronavirus in het land • 15 jaar Facebook",
"body": "<p>Bericht voor Smartschool</p>",
"avo_link": "http://localhost:8080/klaar",
"assets": [
{
"title": "KLAAR: het coronavirus is in het land",
"description": "<p>Het nieuwe coronavirus Covid-19 beheerst al een tijdje het nieuws. Intussen zijn er ook in België besmettingen opgedoken.</p><p><br/></p><p>Wetenschapsjournalist Koen Wauters legt uit welke maatregelen er worden genomen, wat je kan doen om jezelf te beschermen en wat het verschil is met een gewone griep.</p><p><br/></p><p><span style=\"font-size:15px\">Bekijk de interactieve oefening bij deze aflevering en </span><a href=\"https://www.bookwidgets.com/play/NL3SVP\">deel de …
```
> fix(klaar): generate json from new repeated field json structure

- server/src/shared/middleware/session.ts
closes: https://meemoo.atlassian.net/browse/AVO-185
> fix(session): clear redis cache for sessions at 5am, sessions last 24h

- server/src/modules/search/queryBuilder.ts
closes: https://meemoo.atlassian.net/browse/AVO-283
> feat(search): search for keywords in elasticsearch using an AND operator

- server/src/modules/auth/controller.ts
part of: https://meemoo.atlassian.net/browse/AVO-477
5am Belgium time === 3am UTC time
> feat(auth): pass session expiry date with check login response

- server/src/modules/content-pages/controller.ts
- server/src/modules/content-pages/queries.gql.ts
- server/src/shared/middleware/session.ts
closes: https://meemoo.atlassian.net/browse/AVO-217
client PR: https://github.com/viaacode/avo2-client/pull/689
> Fix: media grid/content page route fix view counts

- server/src/modules/video-stills/controller.ts
part of: https://meemoo.atlassian.net/browse/AVO-129
> fix(video-stills): compare time in ms not s

- server/src/modules/auth/idps/hetarchief/route.ts
- server/src/modules/auth/idps/klascement/route.ts
- server/src/modules/auth/idps/smartschool/route.ts
closes: https://meemoo.atlassian.net/browse/AVO-463
> fix(auth): redirect to /start instead of /home or //start

- server/package-lock.json
- server/package.json
- server/src/modules/assets/route.ts
- server/src/modules/assets/service.ts
- server/src/modules/zendesk/service.ts
part of: INFRA-145
also truncate base64 file in logs to 50 chars to avoid huge log entries
> Use asset endpoint from env vars instead of hardcoded version

- server/src/app.ts
- server/src/modules/education-levels/controller.ts
- server/src/modules/education-levels/queries.gql.ts
- server/src/modules/education-levels/route.ts
- server/src/modules/education-levels/service.ts
- server/src/modules/video-stills/controller.ts
Closes: https://meemoo.atlassian.net/secure/RapidBoard.jspa?rapidView=17&projectKey=AVO&modal=detail&selectedIssue=AVO-837
https://github.com/viaacode/avo2-client/pull/794
> feat(education-levels): add route to retrieve education levels.

- server/src/modules/auth/service.ts
- server/src/modules/education-organizations/controller.ts
- server/src/modules/education-organizations/service.ts
closes: https://meemoo.atlassian.net/browse/AVO-941
> feat(edu-orgs): switch from uuid to or_id

- server/src/modules/video-stills/controller.ts
closes: https://meemoo.atlassian.net/browse/AVO-999
client PR: https://github.com/viaacode/avo2-client/pull/813
> fix(video-stills): compare video still times everywhere as milliseconds

- server/src/modules/auth/controller.ts
- server/src/modules/auth/queries.gql.ts
- server/src/modules/auth/service.ts
closes: https://meemoo.atlassian.net/browse/AVO-1014
after you login, you should see an updated date for last_access date in shared.users table
> feat(auth): update last access date when user logs in

- server/src/modules/campaign-monitor/const.ts
- server/src/modules/campaign-monitor/service.ts
You'll need to update your local proxy env vars from 1PW.
> feat(campaign-monitor): expose template as env var

- server/src/modules/campaign-monitor/types.ts
- server/src/modules/content-pages/consts.ts
- server/src/modules/content-pages/controller.ts
- server/src/modules/content-pages/queries.gql.ts
- server/src/modules/content-pages/route.ts
- server/src/modules/content-pages/service.ts
- server/src/modules/content-pages/types.ts
- server/src/modules/klaar/controller.ts
- server/src/modules/player-ticket/controller.ts
- server/src/modules/player-ticket/queries.gql.ts
- server/src/modules/player-ticket/route.ts
partly closes: https://meemoo.atlassian.net/browse/AVO-969
client PR: https://github.com/viaacode/avo2-client/pull/819
> feat(content-pages): resolve media sources server side

- server/src/modules/content-pages/controller.ts
- server/src/modules/organization/queries.gql.ts
- server/src/modules/organization/service.ts
test page: http://localhost:8080/klaar/archief
> fix(content-blocks): resolve org logo for media tile video player

- server/src/modules/auth/helpers/get-user-by-idp-id.ts
- server/src/modules/auth/idps/hetarchief/controller.ts
- server/src/modules/auth/idps/hetarchief/hetarchief.types.ts
- server/src/modules/auth/idps/hetarchief/route.ts
- server/src/modules/auth/idps/klascement/controller.ts
- server/src/modules/auth/idps/smartschool/controller.ts
- server/src/modules/auth/queries.gql.ts
- server/src/modules/auth/service.ts
- server/src/modules/event-logging/route.ts
- server/src/modules/profile/controller.ts
- server/src/shared/middleware/is-authenticated.ts
closes: https://meemoo.atlassian.net/browse/AVO-731
> feat(auth): allow the account manager & ssum to trigger avo user update

- server/src/modules/auth/idps/hetarchief/controller.ts
- server/src/modules/auth/service.ts
- server/src/modules/profile/controller.ts
part of: AVO-731
one symptom was that you could not save subjects from your profile page.
> Fix: fix issues with mapping from ldap to avo fields

- server/src/modules/auth/helpers/get-user-group-ids.ts
- server/src/modules/auth/types.ts
- server/src/modules/content-pages/controller.ts
- server/src/modules/content-pages/queries.gql.ts
- server/src/modules/content-pages/route.ts
- server/src/modules/content-pages/service.ts
- server/src/modules/content-pages/types.ts
- server/src/modules/navigation-items/controller.ts
part of: https://meemoo.atlassian.net/browse/AVO-968
client PR: https://github.com/viaacode/avo2-client/pull/846
> fix(content-page-overview): add route to fetch content pages with filter

- server/src/modules/auth/idp-helper.ts
- server/src/modules/auth/route.ts
- server/src/shared/middleware/session.ts
this route is protected by the same api key as used for the update-user route
> feat(auth): add route to clear the sessions in redis for debugging purp.

- server/src/modules/auth/queries.gql.ts
- server/src/modules/auth/types.ts
part of: https://meemoo.atlassian.net/browse/AVO-870
client PR: https://github.com/viaacode/avo2-client/pull/848
> feat(user): fetch company info with user info

- server/src/modules/auth/idps/hetarchief/controller.ts
- server/src/modules/auth/idps/hetarchief/hetarchief.types.ts
- server/src/modules/auth/idps/hetarchief/route.ts
- server/src/modules/campaign-monitor/controller.ts
- server/src/modules/profile/controller.ts
- server/src/modules/profile/queries.gql.ts
closes: https://meemoo.atlassian.net/browse/AVO-926
voor oormerk wachten we op een deploy van de ldap: https://meemoo.atlassian.net/browse/AVO-926?focusedCommentId=14712
campaign monitor payload:
```json
{
"EmailAddress": "bert.verhelst@studiohyperdrive.be",
"Name": "Bert Verhelst",
"Resubscribe": true,
"ConsentToTrack": "Yes",
"CustomFields": [
{
"Key": "oormerk",
"Value": null
},
{
"Key": "gebruikersgroep",
"Value": "Beheerder"
},
{
"Key": "stamboeknummer",
"Value": "97436428856"
},
{
"Key": "is_uitzondering",
"Value": "true"
},
{
"Key": "firstname",
"Value": "Bert"
},
{
"Key": "lastname",
"Value": "Verhelst"
},
{
"Key": "graad",
"Value": "Secundair onderwijs"
},
{
"Key": "vakken",
"Value": ""
},
{
"Key": "school_postcodes",
"Value": "9000"
},
{
"Key": "school_ids",
"Value": "112102"
}, …
```
> feat(user): copy oormerk and is_exception from ldap + send to CM

- server/src/modules/campaign-monitor/route.ts
closes: https://meemoo.atlassian.net/browse/AVO-1058
> fix(campaign-monitor): always add user to all users list when updating

- server/src/app.ts
- server/src/modules/content-pages/controller.ts
- server/src/modules/organization/organization.spec.ts
- server/src/modules/organization/route.ts
- server/src/modules/organization/service.ts
until this task is fixed: https://meemoo.atlassian.net/browse/DEV-1041
also added option to refesh cache using route with api key
> fix(organisations): disable organisations caching

- server/src/modules/search/service.ts
closes: https://meemoo.atlassian.net/browse/AVO-1115
> fix(search): retry fetch elasticsearch token if error occurs

- server/src/app.ts
- server/src/modules/content-pages/queries.gql.ts
- server/src/modules/content-pages/service.ts
- server/src/modules/sitemap/sitemap.controller.ts
- server/src/modules/sitemap/sitemap.queries.gql.ts
- server/src/modules/sitemap/sitemap.route.ts
- server/src/modules/sitemap/sitemap.service.ts
- server/src/modules/sitemap/sitemap.types.ts
closes: https://meemoo.atlassian.net/browse/AVO-360
For this route we might need a nginx redirect from the client to the proxy
```
http://localhost:8080/sitemap.xml
``` 
to 
```
http://localhost:3000/sitemap
```
> feat(sitemap): add route to generate sitemap dynamically

- server/src/modules/collections/collections.controller.ts
- server/src/modules/collections/collections.queries.gql.ts
- server/src/modules/collections/collections.route.ts
- server/src/modules/collections/collections.service.ts
client twin: https://github.com/viaacode/avo2-client/pull/874
before:
after:
> fix(collections): allow fetch coll. if linked to provided assignment

- server/src/modules/collections/collections.queries.gql.ts
Partially closes: https://meemoo.atlassian.net/secure/RapidBoard.jspa?rapidView=17&projectKey=AVO&modal=detail&selectedIssue=AVO-329
Client twin: https://github.com/viaacode/avo2-client/pull/877
> fix(bundle): return fragment aggregate

- server/package-lock.json
- server/package.json
- server/src/modules/collections/collections.controller.ts
- server/src/modules/collections/collections.queries.gql.ts
- server/src/modules/collections/collections.route.ts
part of: https://meemoo.atlassian.net/browse/AVO-670
> fix(collections): get profile id in a safe way

- server/src/modules/campaign-monitor/controller.ts
- server/src/modules/player-ticket/service.ts
closes: https://meemoo.atlassian.net/browse/AVO-1180
> fix(campaign-monitor-controller): improve logging when edu org not found

- server/src/modules/auth/idps/hetarchief/controller.ts
- server/src/modules/auth/types.ts
closes: https://meemoo.atlassian.net/browse/AVO-1181
> fix(auth): apply to lowercase for organisational_status from ldap

- server/src/modules/search/queryBuilder.ts
closes: https://meemoo.atlassian.net/browse/AVO-1184
> fix(search): add .filter to keyword filter to handle spaces and capitals

- server/src/modules/auth/idps/hetarchief/controller.ts
- server/src/modules/auth/idps/hetarchief/hetarchief.types.ts
- server/src/modules/auth/idps/hetarchief/route.ts
- server/src/modules/auth/idps/klascement/route.ts
- server/src/modules/auth/idps/smartschool/route.ts
- server/src/modules/auth/route.ts
- server/src/modules/campaign-monitor/controller.ts
- server/src/shared/helpers/error.ts
closes: https://meemoo.atlassian.net/browse/AVO-1156
also improved error messages for login/logout routes
fix mapping of business_category and is_exception fields between saml ticket and update-user route
> fix(auth): create user during update user route if user doesn't exist

- server/src/modules/auth/idps/smartschool/controller.ts
closes: https://meemoo.atlassian.net/browse/AVO-1211
> fix(smartschool): log user info when user has no access

- server/src/modules/auth/idps/hetarchief/route.ts
- server/src/modules/auth/service.ts
- server/src/modules/profile/route.ts
closes: https://meemoo.atlassian.net/browse/AVO-1084
multivalue updates zijn nog niet mogelijk in de ldap api https://meemoo.atlassian.net/browse/DEV-1075
> Sync profile info back to ldap

- server/src/modules/auth/idps/hetarchief/controller.ts
- server/src/modules/auth/idps/hetarchief/hetarchief.types.ts
closes: https://meemoo.atlassian.net/browse/AVO-1156
Now oormerk should also be sent to CM:
```json
[
{
"Key": "oormerk",
"Value": "Gemeenschapsonderwijs"
},
{
"Key": "gebruikersgroep",
"Value": "Beheerder"
},
{
"Key": "stamboeknummer",
"Value": "97436428856"
},
{
"Key": "is_uitzondering",
"Value": "true"
},
{
"Key": "firstname",
"Value": "Bert"
},
{
"Key": "lastname",
"Value": "Verhelst"
},
{
"Key": "graad",
"Value": "Lager onderwijs"
},
{
"Key": "vakken",
"Value": "lichamelijke opvoeding, sociale vaardigheden, mens en maatschappij, lichamelijke opvoeding, sociale vaardigheden, mens en maatschappij"
},
{
"Key": "school_postcodes",
"Value": "8791"
},
{
"Key": "school_ids",
"Value": "116111"
},
{
"Key": "school_campus_ids",
"Value": ""
},
{
"Key": "school_namen",
"Value": "Basisschool van …
```
> fix(ldap): read sector field from ldap object and store in title field

- server/src/modules/zendesk/controller.ts
- server/src/modules/zendesk/route.ts
- server/src/modules/zendesk/service.ts
closes: https://meemoo.atlassian.net/browse/AVO-305
related client PR: https://github.com/viaacode/avo2-client/pull/906
> fix(zendesk): send ticket with requester name and email

- server/src/modules/auth/consts.ts
- server/src/modules/auth/idps/smartschool/controller.ts
- server/src/modules/profile/controller.ts
so we can easily identify where all user ids are used and replace them in the future with some sort of identifier from the database
> chore(auth): move user group ids to single enum

- server/src/modules/collections/collections.controller.ts
- server/src/modules/search/controller.ts
Resolves https://meemoo.atlassian.net/browse/AVO-1230.
Client twin: https://github.com/viaacode/avo2-client/pull/913
> Related collections: more like this query niet uitvoeren bij private collecties.

- server/src/modules/collections/collections.controller.ts
Resolves https://meemoo.atlassian.net/browse/AVO-1243.
> feat(collection): auth pop-up when not logged in

- server/package-lock.json
- server/src/modules/content-pages/controller.ts
- server/src/modules/content-pages/route.ts
- server/src/modules/content-pages/service.ts
- server/src/modules/content-pages/types.ts
part of: https://meemoo.atlassian.net/browse/AVO-1142
> feat(content-pages): add option to sort overview results

- server/src/modules/auth/queries.gql.ts
closes: https://meemoo.atlassian.net/browse/AVO-1156
after first login:
> fix(auth): fetch is_exception so we don't override with false

- server/src/modules/organization/service.ts
closes: https://meemoo.atlassian.net/browse/AVO-1196
before this fix we can only find "testbeeld" and no meemoo
after the fix "meemoo" is available:
> fix(orgs): re-enable orgs cron job, use cp_name_catpro not cp_name

- server/src/modules/content-pages/controller.ts
part of: https://meemoo.atlassian.net/browse/AVO-1033
is will start working after this task is implemented:
https://meemoo.atlassian.net/browse/AVO-1107
> fix(content-page): get fragment_count rom ES result

- server/src/modules/auth/controller.ts
- server/src/modules/auth/idps/hetarchief/controller.ts
- server/src/modules/auth/idps/hetarchief/route.ts
- server/src/modules/campaign-monitor/route.ts
- server/src/modules/campaign-monitor/service.ts
- server/src/modules/event-logging/controller.ts
- server/src/modules/event-logging/route.ts
- server/src/modules/event-logging/types.ts
- server/src/modules/profile/route.ts
- server/src/modules/site-variables/controllers/translations.controller.ts
closes: https://meemoo.atlassian.net/browse/AVO-1221
> feat(event-logging): add remaining missing track event calls

- server/src/modules/content-pages/queries.gql.ts
part of: https://meemoo.atlassian.net/browse/AVO-1102
> chore(content-page-gql): improve query names

- server/src/modules/education-organizations/controller.ts
- server/src/modules/education-organizations/service.ts
closes: https://meemoo.atlassian.net/browse/AVO-1271
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/89884638-1b881000-dbca-11ea-872e-ec73f57a35d1.png)![image](https://user-images.githubusercontent.com/1710840/89884647-1e830080-dbca-11ea-90a6-dae54425aabb.png)|![image](https://user-images.githubusercontent.com/1710840/89884617-14f99880-dbca-11ea-8d93-d96f21567080.png)![image](https://user-images.githubusercontent.com/1710840/89884626-175bf280-dbca-11ea-89bd-2583e368d035.png)|
> fix(edu-orgs): use unit zipcode instead of org zipcode

- server/src/modules/collections/collections.controller.ts
- server/src/modules/search/controller.ts
- server/src/modules/search/queryBuilder.ts
- server/src/modules/search/route.ts
- server/src/modules/search/service.ts
Completes meemoo.atlassian.net/browse/AVO-479
Client twin: https://github.com/viaacode/avo2-client/pull/946
> feat(search): retrieve 1000 aggs on search filter search

- server/src/modules/collections/collections.queries.gql.ts
part of: https://meemoo.atlassian.net/browse/AVO-505
> feat(collection): fetch briefing when fetching collection

- server/src/modules/auth/service.ts
partially solves: https://meemoo.atlassian.net/browse/AVO-1275
The remaining issue needs input from Bart
> fix(ldap-sync): send null values instead of empty body for ldap sync

- server/src/modules/auth/idps/hetarchief/service.ts
closes: https://meemoo.atlassian.net/browse/AVO-1173
> fix(hetarchief-service): replace dummy url with login callback url

- server/src/modules/content-pages/controller.ts
closes: https://meemoo.atlassian.net/browse/AVO-940
test page: http://localhost:8080/beheer/content/457
> feat(content-pages-controller): combine manual and search media tiles

- server/src/modules/content-pages/queries.gql.ts
closes: https://meemoo.atlassian.net/browse/AVO-1297
> fix(content-pages): allow owner to preview own content pages

- server/src/modules/auth/idps/hetarchief/controller.ts
- server/src/modules/campaign-monitor/controller.ts
part of: https://meemoo.atlassian.net/browse/AVO-1287
> fix(auth-ldap-sync): switch title to business_category field

- server/src/modules/campaign-monitor/controller.ts
- server/src/modules/campaign-monitor/types.ts
closes: https://meemoo.atlassian.net/browse/AVO-1236
> feat(campaign-monitor-controller): sync edu lvls to edu lvls cm fields

- server/src/modules/auth/service.ts
closes: https://meemoo.atlassian.net/browse/AVO-1275
> fix(auth-service): clear edu levels in ldap by setting empty array

- server/src/modules/search/controller.ts
related to: https://meemoo.atlassian.net/browse/DEV-831
client PR: https://github.com/viaacode/avo2-proxy/pull/224
> fix(search-controller): restore related items search for private coll.

- server/src/modules/content-pages/queries.gql.ts
- server/src/modules/klaar/controller.ts
closes: https://meemoo.atlassian.net/browse/AVO-972
> feat(klaar): add meta_description as the body of the klaar newsletter

- server/src/modules/auth/idps/hetarchief/controller.ts
- server/src/modules/auth/queries.gql.ts
- server/src/modules/auth/service.ts
- server/src/modules/profile/controller.ts
- server/src/modules/profile/route.ts
closes: 
* https://meemoo.atlassian.net/browse/AVO-977
* https://meemoo.atlassian.net/browse/AVO-1275
steps to reproduce:
* create account in ACM with some education levels
* login
* check profile in AVO, should see edu levels
* logout
* edit account in ACM, remove edu levels
* login
* check profile in AVO, should not see any edu levels
> Fix: update user groups

- server/src/modules/search/service.ts
closes: https://meemoo.atlassian.net/browse/AVO-1322
> fix(search): expose elasticsearch search path as env variable

- server/package-lock.json
- server/package.json
- server/src/modules/klaar/controller.ts
closes: https://meemoo.atlassian.net/browse/AVO-1355
http://localhost:3000/klaar/klaar.json
before:
after:
> fix(klaar-controller): strip html from item title and description

- server/src/modules/data/route.ts
- server/src/shared/helpers/map-deep.ts
- server/src/shared/helpers/sanitize/index.ts
- server/src/shared/helpers/sanitize/presets/index.ts
> feat(data): sanitize all html for all variables on the data route

- server/src/modules/auth/idps/hetarchief/controller.ts
closes: https://meemoo.atlassian.net/browse/AVO-1357
remove your stamboek number from your account in acm:
login to avo and check your user detail in the avo admin dashboard
> fix(auth): set stamboek to null if saml ticket stamboek is null

- server/package.json
- server/src/modules/auth/idps/hetarchief/route.ts
- server/src/modules/core/middleware/error.ts
- server/src/modules/organization/service.ts
- server/src/shared/helpers/error.ts
- server/src/shared/helpers/logger.spec.ts
- server/src/shared/helpers/logger.ts
- server/src/shared/helpers/single-line-logging.ts
- server/src/shared/translations/i18n.ts
When SINGLE_LINE_LOGGING === false
When SINGLE_LINE_LOGGING === true
> feat(logger): add SINGLE_LINE_LOGGING env variable support

- server/src/app.ts
- server/src/modules/mam-syncrator/mam-syncrator.controller.ts
- server/src/modules/mam-syncrator/mam-syncrator.route.ts
- server/src/modules/mam-syncrator/mam-syncrator.service.ts
part of: https://meemoo.atlassian.net/browse/AVO-358
> feat(mam-syncrator): add route to trigger mam syncrator delta update

- server/src/modules/sitemap/sitemap.route.ts
part of: https://meemoo.atlassian.net/browse/AVO-1261
> fix(sitemap): change path to sitemap.xml and serve instead of download

- server/src/modules/collections/collections.queries.gql.ts
part of: https://meemoo.atlassian.net/browse/AVO-700
> feat(collections): add relations to item query

- server/package-lock.json
- server/package.json
- server/src/app.ts
- server/src/libs.d.ts
- server/src/modules/collections/collections.queries.gql.ts
- server/src/modules/content-pages/queries.gql.ts
- server/src/modules/subtitles/subtitles.controller.ts
- server/src/modules/subtitles/subtitles.route.ts
- server/src/shared/helpers/stream-to-string.ts
part of: https://meemoo.atlassian.net/browse/AVO-468
example curl request:
```
curl --location --request GET 'http://localhost:3000/subtitles/convert-srt-to-vtt/viaa/MOB/TESTBEELD/a103953270334d40bafd67f95168fdb3a0710db889cd44a2bdbe9694ace80fec/a103953270334d40bafd67f95168fdb3a0710db889cd44a2bdbe9694ace80fec.srt'
```
> feat(subtitles): add route to convert srt subtitles to vtt format

- server/src/modules/data/route.ts
since this mangles urls with query params: https://meemoo.atlassian.net/browse/AVO-1383
> fix(data-route): remove html sanitation from the data route

- server/src/modules/content-pages/queries.gql.ts
part of: https://meemoo.atlassian.net/browse/AVO-1091
> feat(content-page): add link_to to content page label fetch queries

- server/src/modules/player-ticket/service.ts
closes: https://meemoo.atlassian.net/browse/AVO-1384
> fix(player-ticket-service): correctly pass maxage for ticket

- server/package-lock.json
- server/package.json
closes: https://meemoo.atlassian.net/browse/AVO-1373
> chore(package.json): update dependencies to improve security

- server/src/modules/auth/idps/hetarchief/route.ts
- server/src/modules/search/queryBuilder.ts
closes: https://meemoo.atlassian.net/browse/AVO-1392
search for keywords in combination with other filters:
Correctly limit keywords when clearing keyword search field:
> fix(search): include other filters when searching keyword aggs

- server/src/modules/player-ticket/route.ts
closes: https://meemoo.atlassian.net/browse/AVO-1384
> fix(player-ticket-service): get maxage from env var, default to 4h

- server/src/modules/auth/idps/hetarchief/controller.ts
- server/src/modules/auth/idps/hetarchief/hetarchief.types.ts
closes: https://meemoo.atlassian.net/browse/AVO-1390
add orgs in acm:
see orgs on avo profile page
see orgs in admin screen:
see orgs in database:
> fix(archief-controller): correctly sync multiple orgs between avo & ldap

- server/package-lock.json
- server/package.json
part of: https://meemoo.atlassian.net/browse/AVO-1373
since the package has now been updated, we no longer have to force one of it's dependencies to the new version
> chore(package.json): update package to secure version + remove resol.

- server/src/modules/assets/controller.ts
- server/src/modules/assets/route.ts
part of: https://meemoo.atlassian.net/browse/AVO-882
client pr: https://github.com/viaacode/avo2-client/pull/1086
since meemoo wants to use this for file upload as well
> feat(assets): allow more file types

- server/src/modules/auth/idp-helper.ts
- server/src/modules/auth/idps/hetarchief/hetarchief.types.ts
- server/src/modules/auth/service.ts
closes: https://meemoo.atlassian.net/browse/AVO-1370
> feat(auth): set avo id in ldap on create account and update profile

- server/src/modules/auth/idps/hetarchief/controller.ts
- server/src/modules/auth/idps/hetarchief/hetarchief.types.ts
- server/src/modules/auth/idps/hetarchief/service.ts
- server/src/modules/auth/service.ts
- server/src/modules/campaign-monitor/controller.ts
- server/src/modules/education-organizations/controller.ts
- server/src/modules/education-organizations/service.ts
part of: https://meemoo.atlassian.net/browse/AVO-1336
correctly sync orgs when using the ACM sync to avo button
> fix(update-user-route): add format for orgs when synced from ACM

- server/src/modules/profile/controller.ts
closes: https://meemoo.atlassian.net/browse/AVO-1425
> fix(profile-controller): set correct usergroup for student lesgever sec.

- server/src/modules/auth/idps/hetarchief/controller.ts
- server/src/modules/education-organizations/service.ts
- server/src/modules/profile/controller.ts
- server/src/modules/profile/queries.gql.ts
closes: https://meemoo.atlassian.net/browse/AVO-1331
> feat(auth-hetarchief): extract business_category from organisation info

- server/src/modules/auth/idps/hetarchief/route.ts
closes: https://meemoo.atlassian.net/browse/AVO-1424
> fix(auth): logout user out of avo in logout-callback route

- server/src/modules/content-pages/controller.ts
- server/src/modules/content-pages/route.ts
part of: https://meemoo.atlassian.net/browse/AVO-1421
client PR: https://github.com/viaacode/avo2-client/pull/1116
adds content page type and specific error: CONTENT_PAGE_DEPUBLISHED to the error json, so the client can show a specific error message
> feat(content-pages): return depublished indicator and type

- server/src/modules/auth/queries.gql.ts
- server/src/modules/campaign-monitor/campaign-monitor.service.ts
- server/src/modules/profile/controller.ts
- server/src/modules/profile/queries.gql.ts
closes: https://meemoo.atlassian.net/browse/AVO-1234
> fix(campaign-monitor): update user info for all users that where updated

- server/src/modules/auth/idps/hetarchief/controller.ts
closes: https://meemoo.atlassian.net/browse/AVO-1342
> fix(hetarchief-controller): make avo blocked user state have priority

- server/src/modules/profile/route.ts
closes: https://meemoo.atlassian.net/browse/AVO-1436
> fix(profile): only update user info on session if edit own user

- server/src/modules/content-pages/service.ts
closes: https://meemoo.atlassian.net/browse/AVO-1421
|before|after|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/1710840/99696070-90eb6280-2a8e-11eb-8ff3-487a57248780.png)|![image](https://user-images.githubusercontent.com/1710840/99696078-934dbc80-2a8e-11eb-89a5-b986fc9cc0b9.png)|
> fix(content-page): do not include depublished pages in overview

- server/src/modules/campaign-monitor/campaign-monitor.controller.ts
- server/src/modules/campaign-monitor/campaign-monitor.service.ts
closes: https://meemoo.atlassian.net/browse/AVO-1234
> fix(campaign-monitor): set dates as date string + clear empty fields

- server/src/modules/auth/idps/hetarchief/route.ts
- server/src/modules/auth/idps/hetarchief/service.ts
closes: https://meemoo.atlassian.net/browse/AVO-1424
> feat(auth-hetarchief): add route for idp initiated logouts

- server/src/modules/data/data.gql.ts
- server/src/modules/data/data.permissions.ts
- server/src/modules/data/data.service.ts
part of: https://meemoo.atlassian.net/browse/AVO-260
for assignments and collections
> feat(data): add better check for update and delete queries

- server/src/modules/data/data.permissions.ts
- server/src/modules/data/data.service.ts
- server/src/modules/event-logging/service.ts
- server/src/modules/user/user.controller.ts
- server/src/modules/user/user.queries.gql.ts
- server/src/modules/user/user.route.ts
- server/src/modules/user/user.service.ts
- server/src/modules/user/user.types.ts
part of: https://meemoo.atlassian.net/browse/AVO-1336
client PR: https://github.com/viaacode/avo2-client/pull/1134
> feat(user-detail): show blocked and unblocked dates

- server/src/modules/campaign-monitor/campaign-monitor.gql.ts
- server/src/modules/collections/collections.controller.ts
- server/src/modules/collections/collections.queries.gql.ts
- server/src/modules/collections/collections.route.ts
- server/src/modules/collections/collections.service.ts
- server/src/modules/content-pages/controller.ts
- server/src/modules/content-pages/service.ts
part of: https://meemoo.atlassian.net/browse/DEV-1285
> feat(collections): switch assignment id to uuid

- server/src/modules/profile/controller.ts
closes: https://meemoo.atlassian.net/browse/AVO-1336
> fix(profile-controller): remove company if value is null

- server/src/modules/content-pages/consts.ts
- server/src/modules/content-pages/controller.ts
- server/src/modules/content-pages/queries.gql.ts
- server/src/modules/content-pages/types.ts
part of: https://meemoo.atlassian.net/browse/AVO-1471
see client PR for more info: https://github.com/viaacode/avo2-client/pull/1148
> feat(content-pages): add id and duration to video info for content page

- server/package-lock.json
- server/package.json
- server/src/modules/auth/idps/hetarchief/controller.ts
- server/src/modules/data/data.permissions.ts
- server/src/modules/search/queryBuilder.ts
Otherwise this would generate js files in the file structure next to the ts files, which would cause other issues
> fix(package.json): use ts-node to run translation and whitelist scripts

- server/src/modules/auth/idps/hetarchief/controller.ts
- server/src/modules/auth/service.ts
Partially closes: https://meemoo.atlassian.net/browse/AVO-1220
> feat(auth): copy company id from org ids from ldap during login

- server/src/modules/mam-syncrator/mam-syncrator.service.ts
closes: https://meemoo.atlassian.net/browse/DEV-1435
> fix(mam-syncrator): fix issues with triggering sync

- server/src/modules/education-organizations/controller.ts
closes: https://meemoo.atlassian.net/browse/AVO-1540
> fix(edu-orgs): return edu orgsand their units in alphabetical order

- server/src/modules/assets/assets.route.ts
- server/src/modules/organization/organization.spec.ts
- server/src/modules/organization/organization.types.ts
- server/src/modules/organization/service.ts
Mogelijke oplossing voor: https://meemoo.atlassian.net/browse/AVO-1538?searchSessionId=c112fa9e-4058-4a8b-9707-8c819b948fcb&searchObjectId=13871&searchContainerId=10009&searchContentType=issue
> AVO-1538: Potential fix for organization update failure.

- server/src/modules/auth/idps/hetarchief/route.ts
- server/src/modules/campaign-monitor/campaign-monitor.const.ts
- server/src/modules/campaign-monitor/campaign-monitor.service.ts
- server/src/modules/campaign-monitor/campaign-monitor.types.ts
- server/src/modules/user/user.controller.ts
- server/src/modules/user/user.route.ts
- server/src/modules/user/user.service.ts
closes: https://meemoo.atlassian.net/browse/AVO-1514
> fix(user-controller): fix bug when users are deleted using the endpoint

- server/src/modules/mam-syncrator/mam-syncrator.service.ts
closes: https://meemoo.atlassian.net/browse/AVO-1518
> fix(syncrator): add grant_type to access token request

- server/src/modules/campaign-monitor/campaign-monitor.service.ts
Resolves https://meemoo.atlassian.net/browse/AVO-1513
> fix(campaign-monitor): delete from cm on bulk delete users

- server/src/modules/content-pages/controller.ts
- server/src/modules/player-ticket/player-ticket.controller.ts
- server/src/modules/player-ticket/player-ticket.route.ts
- server/src/modules/player-ticket/player-ticket.service.ts
Resolved: https://meemoo.atlassian.net/secure/RapidBoard.jspa?rapidView=32&projectKey=AVO&modal=detail&selectedIssue=AVO-1570
> feat(player-ticket): referrer

- server/src/modules/user/user.queries.gql.ts
Resolves: https://meemoo.atlassian.net/browse/AVO-1577
> fix(admin-users): don’t display deleted users on overview

- server/src/modules/auth/idps/het-archief/het-archief.service.ts
Resolves https://meemoo.atlassian.net/browse/AVO-1334
> fix(ldap): add avo app on unblock

- server/src/modules/auth/idps/het-archief/het-archief.route.ts
- server/src/modules/auth/idps/het-archief/het-archief.service.ts
- server/src/modules/campaign-monitor/campaign-monitor.service.ts
- server/src/modules/user/user.controller.ts
- server/src/modules/user/user.service.ts
> fix(delete-users): add debug logging

- server/src/modules/collections/collections.route.ts
Toevoegen van auth guards om data veiliger te maken zodat mensen die niet ingelogd zijn hier niet aan kunnen.
https://meemoo.atlassian.net/browse/AVO-1648
> fix(collections): add auth guard

- server/src/modules/auth/service.ts
Convert companyId (or_id) to Id, as requested by LDAP api
> fix(organization): convert company or_id to id

- server/src/modules/profile/queries.gql.ts
Fixed updating a user alias if the alias is null in the database
> fix(alias): fixed update alias on null value
